# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
      prefix-development: ci
    groups:
      npm:
        patterns: ["*"]
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
