project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: false

files:
  - source: '/i18n/src/main/en_US/*.toml'
    translation: '/i18n/src/main/%locale_with_underscore%/%original_file_name%.toml'
