project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: '/data/src/lang/en-US/*.json'
    translation: '/data/src/lang/%locale%/%original_file_name%'
