org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.configureondemand=true
# TODO: org.gradle.configuration-cache=true
org.gradle.parallel=true
fabric.loom.multiProjectOptimisation=true

# Internal repository retry settings
# See https://github.com/gradle/gradle/issues/4629#issuecomment-1174938250

# Max repository retries:
systemProp.org.gradle.internal.repository.max.tentative=10
# Initial retry backoff, in milliseconds:
systemProp.org.gradle.internal.repository.initial.backoff=1000
