[mod]
name = "Freecam"
id = "freecam"
group = "net.xolt.freecam"
# Version can specify a semver pre-release, e.g. -alpha.1
# Remember to run :changelog:patchChangelog when updating
version = "1.4.0-alpha.3"
authors = ["hashalite", "Matt Sturgeon"]
license = "MIT"
homepage = "https://www.curseforge.com/minecraft/mc-mods/free-cam"
source = "https://github.com/MinecraftFreecam/Freecam"
issues = "https://github.com/MinecraftFreecam/Freecam/issues"
github_releases = "https://github.com/MinecraftFreecam/Freecam/releases"
curseforge = "https://www.curseforge.com/minecraft/mc-mods/free-cam"
modrinth = "https://modrinth.com/mod/freecam"
crowdin = "https://crowdin.com/project/freecam"
curseforge_id = "557076"
modrinth_id = "XeEZ3fK2"
