# Stonecutter Structured Properties
# https://stonecutter.kikugie.dev/wiki/config/properties#structured-properties
#
# Matching 'tags' are removed from property paths (prefix or suffix).
# Default tags are `sc.branch.id` and `sc.current.project`.
# Tags can be added via `sc.properties.tags()`.
#
# Resolved property paths are stringified as a dotted property keys.
#
# `reqs` versions are parsed as semver constraints, while `deps` are exact versions:
#   https://github.com/z4kn4fein/kotlin-semver#constraints
#
# Fabric: https://fabricmc.net/develop
# NeoForge: https://projects.neoforged.net/neoforged/neoforge
# Cloth Config: https://maven.shedaniel.me/me/shedaniel/cloth/cloth-config-fabric
# ModMenu: https://maven.terraformersmc.com/#browse/browse:maven-terraformers:com%2Fterraformersmc%2Fmodmenu


[relationship]
cloth-config.type = "bundled"
cloth-config.curseforge_slug = "cloth-config"
cloth-config.modrinth_id = "9s6osm5g"


[fabric.relationship]
modmenu.type = "optional"
modmenu.curseforge_slug = "modmenu"
modmenu.modrinth_id = "mOgUt4GM"


["26.3"]
reqs.mc = "26.3.x-0"

deps.cloth = "26.2.155"
reqs.cloth = "~26.3"
# TODO: https://github.com/TerraformersMC/ModMenu/pull/1054
deps.modmenu = "20.0.1"

deps.fabric_api = "0.155.1+26.3"
reqs.fabric_loader = ">=0.18.0"

deps.neoforge_pr = ""
deps.neoforge_version = "26.3.0.0-alpha"
reqs.neoforge_version = ">=26.3.0-0"
reqs.neoforge_loader = ">=1"

# We're not building against cloth-config yet
relationship.cloth-config.type = "none"


["26.2"]
reqs.mc = "~26.2"

deps.cloth = "26.2.155"
reqs.cloth = "~26.2"
deps.modmenu = "20.0.1"

deps.fabric_api = "0.152.2+26.2"
reqs.fabric_loader = ">=0.18.0"

deps.neoforge_version = "26.2.0.6-beta"
reqs.neoforge_version = ">=26.2.0-0"
reqs.neoforge_loader = ">=1"


["26.1"]
supported_mc_versions = ["26.1", "26.1.1", "26.1.2"]
reqs.mc = "~26.1"

deps.cloth = "26.1.154"
reqs.cloth = "~26.1"
deps.modmenu = "18.0.0"

deps.fabric_api = "0.145.4+26.1.2"
reqs.fabric_loader = ">=0.18.0"

deps.neoforge_version = "26.1.2.2-beta"
reqs.neoforge_version = ">=26.1.0-alpha"
reqs.neoforge_loader = ">=1"


["1.21.11"]
reqs.mc = "1.21.11"

deps.cloth = "21.11.153"
reqs.cloth = "~21.11"

deps.fabric_api = "0.139.4+1.21.11"
deps.modmenu = "17.0.0"
reqs.fabric_loader = ">=0.14.0"

deps.neoforge_version = "21.11.6-beta"
deps.neoforge_pr = ""
reqs.neoforge_version = ">=21.9.0-beta"
reqs.neoforge_loader = ">=1"


["1.20.6"]
deps.cloth = "14.0.126"
reqs.cloth = "^14"

deps.fabric_api = "0.100.8+1.20.6"
deps.modmenu = "10.0.0"
reqs.fabric_loader = ">=0.14.0"

deps.neoforge_version = "20.6.139"
deps.neoforge_pr = ""
reqs.neoforge_version = ">=20.6.11-beta"
reqs.neoforge_loader = ">=1"

fabric.supported_mc_versions = ["1.20.5"]
fabric.reqs.mc = "~1.20.5"
neoforge.reqs.mc = "~1.20.6"


["1.19.4"]
reqs.mc = "~1.19.4"
deps.cloth = "10.1.117"
reqs.cloth = "^10.1"

deps.fabric_api = "0.87.2+1.19.4"
deps.modmenu = "6.3.1"
reqs.fabric_loader = ">=0.12.11"

deps.forge_version = "45.2.6"
reqs.forge_version = ">=45"
reqs.forge_loader = ">=45"


["1.18.2"]
reqs.mc = "~1.18.2"
deps.cloth = "6.5.102"
reqs.cloth = "^6"

deps.fabric_api = "0.77.0+1.18.2"
deps.modmenu = "3.2.5"
reqs.fabric_loader = ">=0.12.11"

deps.forge_version = "40.2.14"
reqs.forge_version = ">=40"
reqs.forge_loader = ">=40"


["1.17.1"]
deps.cloth = "5.3.63"
reqs.cloth = "^5"

deps.fabric_api = "0.46.1+1.17"
deps.modmenu = "2.0.17"
reqs.fabric_loader = ">=0.12.11"

deps.forge_version = "37.1.1"
reqs.forge_version = ">=37"
reqs.forge_loader = ">=37"

fabric.supported_mc_versions = ["1.17"]
fabric.reqs.mc = "~1.17"
forge.reqs.mc = "~1.17.1"


["1.16.5"]
supported_mc_versions = ["1.16.2", "1.16.3", "1.16.4"]
reqs.mc = "~1.16.2"

deps.cloth = "4.17.101"

deps.fabric_api = "0.42.0+1.16"
deps.modmenu = "1.16.23"
reqs.fabric_loader = ">=0.12.11"

deps.forge_version = "36.2.41"
reqs.forge_version = ">=34"
reqs.forge_loader = ">=34"
