blank_issues_enabled: false
contact_links:
    - name: Translations
      url: https://crowdin.com/project/freecam
      about: You can help improve Freecam's translations using Crowdin.
    - name: Questions and discussion
      url: https://github.com/MinecraftFreecam/Freecam/discussions/new/choose
      about: If the options above don't seem right, you may be better off starting a "discussion" instead.
