import io.github.z4kn4fein.semver.constraints.toMavenFormat
import net.xolt.freecam.gradle.NeoForgeModsTomlTask
import net.xolt.freecam.model.FmlDependencyType

plugins {
    alias(libs.plugins.moddev)
    alias(libs.plugins.fletchingtable.neoforge)
    id("freecam.loaders")
    id("freecam.fml")
    id("freecam.shadow")
}

val mixinConfigNames = listOf(
    "freecam-common.mixins.json",
    "freecam-neoforge.mixins.json",
)

fletchingTable {
    accessConverter.register(sourceSets.main) {
        // During processResources, Fletching Table will exclude this file
        // and generate a META-INF/accesstransformer.cfg from it
        add("freecam.accesswidener")
    }
}

neoForge {
    enable {
        version = meta.deps["neoforge_version"]
    }
}

dependencies {
    if (sc.current.parsed >= "26.2") {
        // In 26.2 NeoForge introduced a new ModListScreen, which shows a 24px icon.
        // We use a 96px icon because it is a multiple of 24.
        extraResources(project(":branding", configuration = "icon_96"))
    }
    bundle(api(project(":config"))!!)
    sc.node.sibling("cloth-config")?.let {
        val clothVersion = requireNotNull(meta.deps["cloth"]) {
            "Missing deps.cloth for ${project.path}"
        }
        val clothConstraint = requireNotNull(meta.reqs["cloth"]) {
            "Missing reqs.cloth for ${project.path}"
        }
        bundle(implementation(project(path = it.project.path, configuration = "namedElements"))!!)
        jarJar(implementation("me.shedaniel.cloth:cloth-config-neoforge") {
            version {
                prefer(clothVersion)
                strictly(clothConstraint.toMavenFormat())
            }
        })
    } ?: logger.warn("No :cloth-config project for ${project.path}")
}

neoForge {
    // Use the accesstransformer generated by Fletching Table
    accessTransformers.from(tasks.processResources.map {
        it.destinationDir.resolve("META-INF/accesstransformer.cfg")
    })
    validateAccessTransformers = true

    runs {
        register("client") {
            client()
            ideName = "NeoForge Client (${project.path})"
        }
//        register("server") {
//            server()
//            ideName = "NeoForge Server (${project.path})"
//        }
    }

    mods {
        register(meta.id) {
            sourceSet(sourceSets.main.get())

            // Mark internal dependencies as part of the mod, so their classes are loaded in dev runs.
            sourceSet(sourceSets.create("bundled") {
                sequenceOf(java, resources).forEach {
                    it.setSrcDirs(emptySet<String>())
                }
                output.dir(configurations.bundle)
            })
        }
    }
}

tasks.register<Copy>("buildAndCollect") {
    group = "build"
    from(tasks.shadowJar.flatMap { it.archiveFile })
    into(rootProject.layout.buildDirectory.file("libs/${meta.buildDir}"))
    dependsOn(tasks.build)
}

tasks.generateReleaseMetadata {
    artifactFileName = tasks.shadowJar.flatMap { it.archiveFileName }
}

tasks.named("createMinecraftArtifacts") {
    dependsOn(tasks.processResources)
}

val generateModsTomlTask = tasks.register<NeoForgeModsTomlTask>("generateModsToml") {
    description = "Generate the neoforge.mods.toml file"

    toml {
        loaderVersion = meta.reqs["neoforge_loader"]?.toMavenFormat()
        issueTrackerURL = meta.issuesUrl.toString()
        license = meta.license

        mod(meta.id) {
            displayName = meta.name
            version = meta.version.toString()
            description = meta.description
            authors = meta.authors.joinToString(", ")
            displayURL = meta.homepageUrl.toString()
            if (sc.current.parsed >= "26.2") {
                bannerFile = "icon.png"
                iconFile = "icon-96.png"
                iconBlur = true
            }
            if (sc.current.parsed <= "26.2") {
                logoFile = "icon.png"
                logoBlur = true
            }
        }

        dependency(meta.id, "minecraft") {
            versionRange = meta.reqs["mc"]?.toMavenFormat()
            ordering = "NONE"
            side = "CLIENT"
        }
        dependency(meta.id, "neoforge") {
            versionRange = meta.reqs["neoforge_version"]?.toMavenFormat()
            ordering = "NONE"
            side = "CLIENT"
        }
        dependency(meta.id, "cloth_config") {
            versionRange = meta.reqs["cloth"]?.toMavenFormat()
            type = FmlDependencyType.OPTIONAL
            ordering = "NONE"
            side = "CLIENT"
        }

        mixinConfigNames.forEach(::mixin)
    }
}

tasks.processResources {
    from(generateModsTomlTask) {
        into("META-INF")
    }

    filesMatching("freecam-neoforge.mixins.json") {
        expand("mixinCompatLevel" to "JAVA_${meta.javaVersion}")
    }

    inputs.properties("java_version" to meta.javaVersion)
}

tasks.shadowJar {
    from(tasks.jarJar)
}
