import io.github.z4kn4fein.semver.constraints.toMavenFormat
import net.xolt.freecam.gradle.NeoForgeModsTomlTask
import net.xolt.freecam.model.FmlDependencyType

plugins {
    alias(libs.plugins.moddev)
    alias(libs.plugins.fletchingtable.neoforge)
    id("freecam.loaders")
    id("freecam.fml")
}

val mixinConfigNames = listOf(
    "freecam-common.mixins.json",
    "freecam-neoforge.mixins.json",
)

fletchingTable {
    accessConverter.register(sourceSets.main) {
        // During processResources, Fletching Table will exclude this file
        // and generate a META-INF/accesstransformer.cfg from it
        add("freecam.accesswidener")
    }
}

neoForge {
    enable {
        version = meta.deps["neoforge_version"]
    }
}

dependencies {
    sc.node.sibling("cloth-config")?.let {
        val clothVersion = requireNotNull(meta.deps["cloth"]) {
            "Missing deps.cloth for ${project.path}"
        }
        val clothConstraint = requireNotNull(meta.reqs["cloth"]) {
            "Missing reqs.cloth for ${project.path}"
        }
        jarJar(implementation(project(path = it.project.path, configuration = "namedElements")) as Any)
        jarJar(implementation("me.shedaniel.cloth:cloth-config-neoforge") {
            version {
                prefer(clothVersion)
                strictly(clothConstraint.toMavenFormat())
            }
        })
    } ?: logger.warn("No :cloth-config project for ${project.path}")
}

neoForge {
    // Use the accesstransformer generated by Fletching Table
    accessTransformers.from(tasks.processResources.map {
        it.destinationDir.resolve("META-INF/accesstransformer.cfg")
    })
    validateAccessTransformers = true

    runs {
        register("client") {
            client()
            ideName = "NeoForge Client (${project.path})"
        }
//        register("server") {
//            server()
//            ideName = "NeoForge Server (${project.path})"
//        }
    }

    mods {
        register(meta.id) {
            sourceSet(sourceSets.main.get())
        }
    }
}

sourceSets.main {
    resources.srcDir("src/generated/resources")
}

tasks.register<Copy>("buildAndCollect") {
    group = "build"
    from(tasks.jar.map { it.archiveFile })
    into(rootProject.layout.buildDirectory.file("libs/${meta.buildDir}"))
    dependsOn(tasks.build)
}

tasks.named("createMinecraftArtifacts") {
    dependsOn(tasks.processResources)
}

val generateModsTomlTask = tasks.register<NeoForgeModsTomlTask>("generateModsToml") {
    description = "Generate the neoforge.mods.toml file"

    toml {
        loaderVersion = meta.reqs["neoforge_loader"]?.toMavenFormat()
        issueTrackerURL = meta.issuesUrl.toString()
        license = meta.license

        mod(meta.id) {
            displayName = meta.name
            version = meta.version.toString()
            description = meta.description
            authors = meta.authors.joinToString(", ")
            displayURL = meta.homepageUrl.toString()
            logoFile = "icon.png"
            logoBlur = true
        }

        dependency(meta.id, "minecraft") {
            versionRange = meta.reqs["mc"]?.toMavenFormat()
            ordering = "NONE"
            side = "CLIENT"
        }
        dependency(meta.id, "neoforge") {
            versionRange = meta.reqs["neoforge_version"]?.toMavenFormat()
            ordering = "NONE"
            side = "CLIENT"
        }
        dependency(meta.id, "cloth_config") {
            versionRange = meta.reqs["cloth"]?.toMavenFormat()
            type = FmlDependencyType.OPTIONAL
            ordering = "NONE"
            side = "CLIENT"
        }

        mixinConfigNames.forEach(::mixin)
    }
}

tasks.processResources {
    from(generateModsTomlTask) {
        into("META-INF")
    }

    filesMatching("freecam-neoforge.mixins.json") {
        expand("mixinCompatLevel" to "JAVA_${meta.javaVersion}")
    }

    inputs.properties("java_version" to meta.javaVersion)
}
