[[build]]
name = "Tooling"
gradle_args = ["--project-dir", "build-logic", ":check"]

[[build]]
name = "Release publisher"
gradle_args = [":publish:check", ":publish:distTar"]
upload.path = "publish/build/distributions/*.tar"
upload.archive = false
upload.days = 5
