[[build]]
name = "Build logic tests"
gradle_args = ["--project-dir", "build-logic", ":check"]

[[build]]
name = "Build release publisher"
gradle_args = [":publish:check", ":publish:distTar"]
upload_name = "release-publisher"
upload_path = "publish/build/distributions/*.tar"
upload_days = 5
