name: Crowdin (Upload Translations)

on:
  workflow_dispatch: # Allow running manually
## (Disable automatic runs for now)
#  push: # Run when a non-en_us lang file is modified on the main branch
#    branches:
#      - main
#    paths:
#      - 'data/src/lang/*/*.json'
#      - '!data/src/lang/en-US/*'

# Queue this workflow after others in the 'crowdin' group, to avoid concurrency issues.
concurrency:
  group: crowdin

jobs:
  upload_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Translations
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: true
          download_translations: false
          crowdin_branch_name: ${{ github.ref_name }}
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}