name: Comment

on:
  pull_request_target:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize

# Group workflow runs by event + PR.
# New runs cancel any pending run.
# In-progress runs are allowed to complete.
concurrency:
  group: pr-comment-${{ github.event.number }}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  prepare:
    name: Setup
    uses: ./.github/workflows/prepare.yaml
    permissions:
      contents: read
    with:
      changelog: true


  find_build:
    name: Find build
    runs-on: ubuntu-slim
    timeout-minutes: 10

    permissions:
      actions: read # For listing workflow runs

    outputs:
      id: ${{ steps.find.outputs.id }}

    steps:
      - name: Find workflow run
        id: find
        timeout-minutes: 6 # deadline + 1
        uses: actions/github-script@v8
        with:
          script: |
            const { owner, repo } = context.repo
            const head_sha = context.payload.pull_request.head.sha
            const deadline = Date.now() + 5 * 60_000 // 5 minutes

            const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))
            const backoff = (() => {
              let delay = 5_000
              return async () => {
                await sleep(delay)
                delay = Math.min(delay * 1.5, 15_000)
              }
            })()

            core.info("Polling for 'build.yml' workflow run")
            const workflow = await (async () => {
              while (Date.now() < deadline) {
                const iterator = github.paginate.iterator(
                  github.rest.actions.listWorkflowRunsForRepo,
                  {
                    owner,
                    repo,
                    event: "pull_request",
                    head_sha,
                    exclude_pull_requests: true,
                    per_page: 100, // Minimize requests
                  }
                )

                for await (const page of iterator) {
                  const match = page.data
                    .sort((a, b) => new Date(b.created_at) - new Date(a.created_at))
                    .find(run => run.path === ".github/workflows/build.yaml")
                  if (match) return match
                }

                await backoff()
              }
            })()

            if (!workflow) {
              core.setFailed("Timed out looking for build workflow run")
              return
            }

            core.setOutput("id", workflow.id)

  sync:
    name: Sync
    runs-on: ubuntu-slim
    needs: [prepare, find_build]
    timeout-minutes: 15

    permissions:
      actions: read # For downloading artifacts
      issues: write # For posting comments
      pull-requests: write # For posting comments

    steps:
      - name: Wait for changelog
        id: find
        if: needs.prepare.outputs.changelog_comment
        timeout-minutes: 11 # deadline + 1
        uses: actions/github-script@v8
        env:
          RUN_ID: ${{ needs.find_build.outputs.id }}
        with:
          script: |
            const { owner, repo } = context.repo
            const run_id = process.env.RUN_ID
            const deadline = Date.now() + 10 * 60_000 // 10 minutes

            const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))
            const backoff = (() => {
              let delay = 3_000

              return async () => {
                await sleep(delay)
                delay = Math.min(delay * 1.25, 20_000)
              }
            })()

            // Due to Java & Gradle setup, the changelog usually takes ~1m to build.
            // Wait 45s before polling, to reduce wasteful API calls.
            core.info("Waiting 45s before starting...")
            await sleep(45_000)

            core.info("Polling for changelog.md")
            const changelog = await (async () => {
              while (Date.now() < deadline) {
                const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                  owner,
                  repo,
                  run_id,
                })

                const match = artifacts.data.artifacts.find(a => a.name === "changelog.md")
                if (match) return match

                await backoff()
              }
            })()

            if (!changelog) {
              core.setFailed("Timed out waiting for changelog artifact")
              return
            }

            core.setOutput("id", changelog.id)

      - name: Download artifact
        id: download
        if: steps.find.outputs.id
        uses: actions/download-artifact@v8
        with:
          run-id: ${{ needs.find_build.outputs.id }}
          artifact-ids: ${{ steps.find.outputs.id }}
          github-token: ${{ github.token }}

      - name: Sync PR comment
        uses: actions/github-script@v8
        with:
          script: |
            const { readFileSync } = require("fs")

            const { owner, repo } = context.repo
            const issue_number = context.payload.number
            const botId = 41898282 // github-actions[bot]
            const marker = "<!-- changelog-preview -->"

            // Read the optional changelog body
            const body = (function() {
              try {
                 return marker + "\n\n# 📦 Changelog\n\n"
                     + readFileSync("changelog.md", "utf8")
              } catch (err) {
                if (err.code !== 'ENOENT') throw err
                return null
              }
            })()

            // Find an existing changelog comment
            const existing = await (async function() {
              const iterator = github.paginate.iterator(
                github.rest.issues.listComments,
                { owner, repo, issue_number }
              )

              for await (const page of iterator) {
                const match = page.data.find(comment =>
                    comment.user?.id === botId &&
                    comment.body?.trimStart().startsWith(marker)
                )
                if (match) return match
              }

              return null
            })()

            if (!body) {
              if (!existing) {
                core.notice("No changelog and no existing comment")
                return
              }

              core.notice(`Minimizing existing changelog comment (${existing.id})`)
              await github.graphql(
                `mutation($id: ID!) {
                  minimizeComment(input: { subjectId: $id, classifier: OUTDATED }) {
                    clientMutationId
                  }
                }`,
                { id: existing.node_id }
              )
              return
            }

            if (existing) {
              core.notice(`Updating and un-minimizing existing changelog comment (${existing.id})`)
              // Update body if necessary
              if (body.trim() !== existing.body?.trim()) {
                await github.rest.issues.updateComment({
                  owner,
                  repo,
                  comment_id: existing.id,
                  body,
                })
              }
              // Then un-minimize
              await github.graphql(
                `mutation($id: ID!) {
                  unminimizeComment(input: { subjectId: $id }) {
                    clientMutationId
                  }
                }`,
                { id: existing.node_id }
              )
              return
            }

            // Create a new comment
            core.notice("Creating a new changelog comment")
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body,
            })
