name: Publish

on:
  workflow_call:
    inputs:
      ref:
        description: Ref to publish
        type: string
        default: ${{ github.sha }}
      dry-run:
        description: Dry run
        type: boolean
        default: false
    outputs: {}
    secrets: {}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  release:
    name: ${{ inputs.dry-run && 'dry run' || 'Release' }}
    runs-on: ubuntu-slim
    timeout-minutes: 30

    permissions:
      # Grant 'write' to create releases.
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Publish release
        env:
          dry_run: ${{ inputs.dry-run || '' }}
          ref: ${{ inputs.ref }}
          GH_TOKEN: ${{ github.token }}
        run: |
          set -o pipefail
          shopt -s nullglob

          meta=artifacts/release-metadata.json
          files=( artifacts/release-*.json )
          [ ${#files[@]} = 1 ] || {
            echo "::error::Found ${#files[@]} release json artifacts, expected 1"
            exit 1
          }
          mv "${files[0]}" "$meta"

          version=$(jq .mod_version "$meta" --raw-output)
          title=$(jq .display_name "$meta" --raw-output)
          jq .changelog "$meta" --raw-output > changelog.md

          args=(
            --repo "$GITHUB_REPOSITORY"
            release create "v$version"
            --target "$ref"
            --title "$title"
            --notes-file changelog.md
          )

          jq '.release_type == "release"' "$meta" --exit-status >/dev/null || {
            args+=( --prerelease )
          }

          args+=( "$meta" artifacts/*.jar )

          if [ -n "$dry_run" ]; then
            echo "Dry run:"
            printf ' %q' gh "${args[@]}"
            echo
          else
            gh "${args[@]}"
          fi
