name: Publish

on:
  workflow_call:
    inputs:
      ref:
        description: Ref to publish
        type: string
        default: ${{ github.sha }}
      dry-run:
        description: Dry run
        type: boolean
        default: false
    secrets:
       MODRINTH_TOKEN:
         description: Modrinth API token (required unless dry-run)
         required: false
       CURSEFORGE_TOKEN:
         description: CurseForge API token (required unless dry-run)
         required: false
    outputs: {}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  release:
    name: ${{ inputs.dry-run && 'dry run' || 'Release' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      # Grant 'write' to create releases.
      contents: write

    steps:
      - name: Checkout changelog
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref }}
          sparse-checkout: |
            knope.toml
            metadata.toml
            CHANGELOG.md
          sparse-checkout-cone-mode: false

      - name: Install Knope
        uses: knope-dev/action@v2.1.2
        with:
          # TODO: keep up to date
          version: 0.23.0

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Prepare Release Notes
        run: |
          knope print-release-notes > release-notes.md

      - name: Prepare Release Metadata
        run: |
          shopt -s nullglob

          files=( artifacts/release-*.json )
          [ ${#files[@]} = 1 ] || {
            echo "::error::Found ${#files[@]} release json artifacts, expected 1"
            exit 1
          }
          mv "${files[0]}" artifacts/release-metadata.json

      - name: Publish GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          knope release ${{ inputs.dry-run && '--dry-run' || '' }}

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin

      - name: Setup Freecam Publisher
        uses: MinecraftFreecam/Publisher@v0.0.6

      - name: Publish to CurseForge & Modrinth
        env:
          dry_run: ${{ inputs.dry-run || '' }}
          MODRINTH_TOKEN: ${{ inputs.dry-run && 'token' || secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ inputs.dry-run && 'token' || secrets.CURSEFORGE_TOKEN }}
        run: |
          echo "::notice::Using $(freecam-publish --version)"
          args=(
            --release-notes release-notes.md
            --metadata artifacts/release-metadata.json
            artifacts
          )
          if [ -n "$dry_run" ]; then
            echo "Dry run:"
            args+=( --dry-run )
          fi
          freecam-publish "${args[@]}"
