name: Push

on:
  push:
    branches:
      - main

# Group workflow runs by ref.
# New runs cancel any pending run.
# In-progress runs are allowed to complete.
concurrency:
  group: push-${{ github.ref }}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  prepare:
    name: Setup
    uses: ./.github/workflows/prepare.yaml
    permissions:
      contents: read
    with:
      release: true
      matrix: true

  create_release_pr:
    # Create a release PR unless this push event is the result of merging a release PR.
    # If `prepare` finds un unpublished version, that means a release PR was merged.
    if: ${{ !needs.prepare.outputs.do_release }}

    name: Create Release PR
    uses: ./.github/workflows/create-release-pr.yaml
    needs: prepare
    permissions:
      contents: write
      pull-requests: write
    secrets:
      FREECAM_CI_APP_PRIVATE_KEY: ${{ secrets.FREECAM_CI_APP_PRIVATE_KEY }}

  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    needs: prepare
    permissions:
      contents: read
    with:
      matrix: ${{ needs.prepare.outputs.matrix }}

  publish:
    if: needs.prepare.outputs.do_release
    name: Publish
    uses: ./.github/workflows/publish.yaml
    needs:
      - prepare
      - build
    permissions:
      contents: write
    secrets:
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
